<a href="https://colab.research.google.com/github/B1cyruz/B1cyruz/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [5]:
vector = np.array([25,18,42,49,78,73,48])
print(vector)

[25 18 42 49 78 73 48]


In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
